export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};
import SubmitProvider from '../context/SubmitContext';
import './globals.css';
import Footer from '@/components/nav/footer/Footer';
import Header from '@/components/nav/header/Header';
import { Container } from '@mui/material';
import { body_container_props } from '@/mui_props/box';
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <SubmitProvider>
        <body style={{ paddingTop: '50px', paddingBottom: '100px' }}>
          <Header />
          <Container sx={body_container_props}>{children}</Container>
          <Footer />
        </body>
      </SubmitProvider>
    </html>
  );
}
