"""migration

Revision ID: 40bfa3e1d367
Revises: e9f70564c371
Create Date: 2024-06-20 16:50:04.023307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40bfa3e1d367'
down_revision = 'e9f70564c371'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('system_publisher')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_publisher',
    sa.Column('system_id', sa.INTEGER(), nullable=False),
    sa.Column('publisher_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['publisher_id'], ['publishers.id'], ),
    sa.ForeignKeyConstraint(['system_id'], ['systems.id'], ),
    sa.PrimaryKeyConstraint('system_id', 'publisher_id')
    )
    # ### end Alembic commands ###
