"""games and systems table

Revision ID: e8bce9f77a1f
Revises: fb73e1db93d3
Create Date: 2024-06-17 04:28:35.560110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8bce9f77a1f'
down_revision = 'fb73e1db93d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('release_year', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_column('release_year')

    # ### end Alembic commands ###
