"""games and systems table

Revision ID: e9f70564c371
Revises: e8bce9f77a1f
Create Date: 2024-06-17 16:35:06.244330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9f70564c371'
down_revision = 'e8bce9f77a1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.alter_column('release_year',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.alter_column('release_year',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
